name:                unordered-intmap
synopsis: A specialization of `HashMap Int v`
version:             0.1.0.0
homepage:            https://github.com/ethercrow/unordered-intmap
license:             BSD3
author:              Dmitry Ivanov
maintainer:          ethercrow@gmail.com
copyright:           2017 Dmitry Ivanov
category:            Data
extra-source-files:
- README.rst

dependencies:
- base >= 4.7 && < 5
- deepseq
- primitive >= 0.6.2

ghc-options: -Wall -ferror-spans

library:
    source-dirs: src
    exposed-modules:
    - Data.Unordered.IntMap

tests:
    props:
        source-dirs: test
        main: UnorderedIntMapProperties.hs
        dependencies:
            - unordered-intmap
            - containers
            - QuickCheck
            - tasty
            - tasty-quickcheck